In [117]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import MinMaxScaler,LabelEncoder
from sklearn.model_selection import train_test_split

In [118]:
df = pd.read_csv("Housing.csv")

In [119]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [120]:
df.shape

(545, 13)

In [121]:
df['furnishingstatus'].value_counts()

furnishingstatus
semi-furnished    227
unfurnished       178
furnished         140
Name: count, dtype: int64

In [122]:
df = df.drop("furnishingstatus", axis=1)

In [123]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no

In [124]:
Y = df[['price']]
X = df.drop(['price'], axis = 1)

In [125]:
X.head()

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea
0,7420,4,2,3,yes,no,no,no,yes,2,yes
1,8960,4,4,4,yes,no,no,no,yes,3,no
2,9960,3,2,2,yes,no,yes,no,no,2,yes
3,7500,4,2,2,yes,no,yes,no,yes,3,yes
4,7420,4,1,2,yes,yes,yes,no,yes,2,no

In [126]:
Y

        price
0    13300000
1    12250000
2    12250000
3    12215000
4    11410000
..        ...
540   1820000
541   1767150
542   1750000
543   1750000
544   1750000

[545 rows x 1 columns]

In [127]:
cat_col = ["mainroad",	"guestroom",	"basement",	"hotwaterheating","airconditioning",	"prefarea",]

In [128]:
for i in cat_col:
  df[i] = df[i].replace({"yes":1, "no":0})

C:\Users\ABDULLAH AL MASUM\AppData\Local\Temp\ipykernel_19232\2623045940.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[i] = df[i].replace({"yes":1, "no":0})

In [129]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea
0,13300000,7420,4,2,3,1,0,0,0,1,2,1
1,12250000,8960,4,4,4,1,0,0,0,1,3,0
2,12250000,9960,3,2,2,1,0,1,0,0,2,1
3,12215000,7500,4,2,2,1,0,1,0,1,3,1
4,11410000,7420,4,1,2,1,1,1,0,1,2,0

In [130]:
x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size=.2, random_state=42)

In [131]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((436, 11), (109, 11), (436, 1), (109, 1))

In [132]:
mms = MinMaxScaler()

In [134]:
x_train = x_train.replace({'yes': 1, 'no': 0})
x_test = x_test.replace({'yes': 1, 'no': 0})

C:\Users\ABDULLAH AL MASUM\AppData\Local\Temp\ipykernel_19232\605635569.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  x_train = x_train.replace({'yes': 1, 'no': 0})
C:\Users\ABDULLAH AL MASUM\AppData\Local\Temp\ipykernel_19232\605635569.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  x_test = x_test.replace({'yes': 1, 'no': 0})

In [135]:
x_train = mms.fit_transform(x_train)
x_test = mms.transform(x_test)

In [136]:
lr = LinearRegression()

In [137]:
model = lr.fit(x_train, y_train)

In [139]:
y_pred = model.predict(x_test)

In [143]:
model.score(x_test, y_test)

0.6437296086614106

In [144]:
import pickle

with open("model.pkl", "wb") as f:
  pickle.dump(model, f)

In [145]:
df.columns

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea'],
      dtype='object')